### ISSUE TITLE
[Bug] Missing icon (broken links) in readme

### ISSUE THREAD

**Issue by PySimpleGUI** [FHPythonUtils/Cli2Gui#1]
## Question
- [x ] I have read the comment above and have completed each step

## Bug
- [x ] I have read the comment above and have completed each step
- [x ] I have filled out the system info
- [x ] I have described the bug, filled in the expected outcome and the actual
outcome including screenshots where appropriate

### Describe the bug

This is what's shown on the homepage / readme

![image](https://user-images.githubusercontent.com/46163555/76633975-f65c7c00-651b-11ea-9e3f-ffd05df6e994.png)

### Expected outcome

Icon should be shown

**Comment by FredHappyface** [comment]
Hello.

Thanks for the issue. Unfortunately I haven't got around to creating a project icon yet

I'll aim to get one out in the next few weeks (should be early next week all being well)

**Comment by FredHappyface** [comment]
Hello,

I've added the project icon now :smile:. Please do let me know if you have any more queries (if not, I'll close this in a few days)
