### ISSUE TITLE
Support for parser.add_subparsers()

### ISSUE THREAD

**Issue by Evidlo** [FHPythonUtils/Cli2Gui#10]
When `parser.add_subparsers()` is used, Cli2Gui fails with the message

```
[evan@blackbox picklecast] python /tmp/test.py
Traceback (most recent call last):
  File "/tmp/test.py", line 30, in <module>
    gui()
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/cli2gui/decorators.py", line 286, in inner
    return callingFunction(*args, **kwargs)
  File "/tmp/test.py", line 14, in main
    args = parser.parse_args()
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/cli2gui/decorators.py", line 249, in runCli2Gui
    buildSpec = createFromParser(
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/cli2gui/decorators.py", line 85, in createFromParser
    return FullBuildSpec(**convertMap["self"][parser](selfParser), **buildSpec)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/cli2gui/tojson/argparse2json.py", line 186, in convert
    for _, subparser in iterParsers(parser):
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/cli2gui/tojson/argparse2json.py", line 42, in iterParsers
    ].choices.arg_items()
AttributeError: 'dict' object has no attribute 'arg_items'
```

``` python
#!/usr/bin/env python3
from cli2gui import Cli2Gui
import argparse

def run(args):
    print(args.arg)

def main():
    parser = argparse.ArgumentParser(description="this is an example parser")
    parser.add_argument("arg", type=str, help="positional arg")

    parser.add_subparsers()

    args = parser.parse_args()
    run(args)

decorator_function = Cli2Gui(
    run_function=run,
    auto_enable=True,
)

gui = decorator_function(main)

if __name__ == "__main__":
    gui()
```

Ideally Cli2Gui would support these subparsers (perhaps as additional tabs in the GUI), but at least they could be ignored and not cause an exception.

**Comment by FredHappyface** [comment]
Hey, cheers for the issue and apologies for the delayed response 

Probably best to opt for the ignore case for now as there's a decent chunk of work there to remind myself how things work and then to investigate subparsers. Not sure if https://github.com/chriskiehl/Gooey has what you need here?

**Comment by FredHappyface** [comment]
Taken a look and this is the best I can do thus far:


![image](https://user-images.githubusercontent.com/41634689/188229736-534e36c9-ac93-49b9-91bd-1b8cc3e52224.png)

```
Namespace(arg='foo', **{'==SUPPRESS==': '???'})
```

**Comment by Evidlo** [comment]
I like Cli2Gui because I can continue to use argparse.

Thanks for the work on this.  Why not simply ignore the subparser instead of adding that `==SUPPRESS==` argument?  That might be confusing to end users.

**Comment by FredHappyface** [comment]
Argparse adds the ==suppress== arg. Seems to contain info on the subparser. So if you give it a description then it renders in place of none. There's an example under the tests
