### ISSUE TITLE
Need help to setup a predefined path for file browser widget when chosen

### ISSUE THREAD

**Issue by Ms-Ajith** [FHPythonUtils/Cli2Gui#12]
Hello Guys. I am new to Cli2gui and argparser and I am trying to create a GUI for my work. So for fileType (type), how can I set up a predefined dir to open as default rather than select every time?

**Comment by FredHappyface** [comment]
Hi thanks for opening the issue. Currently this is not supported. The file open dialogue is provided by pysimplegui so may be worth checking that out

**Comment by Ms-Ajith** [comment]
Thank you :)
