### ISSUE TITLE
Bug: cli2gui will not handle close event for dearPyGui

### ISSUE THREAD

**Issue by mokurin000** [FHPythonUtils/Cli2Gui#18]
## Before You Begin

Before proceeding, please make sure to follow these steps:

- [x] I have checked for similar issues in the project's issue tracker.
- [x] I have searched closed issues to see if a similar problem was reported
  before.

## Issue Details

Once you close the program via close button on system decoration, rather than the embeded Exit button, cli2gui will call run callback with None as args.

### Expected Behavior

Cli2Gui should terminate the program normally.

### Actual Behavior

This will cause a crash after closing window, like:

```python
    if not args.skip_edge:
           ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'skip_edge'
```

## System Information

Please provide the following additional information about your system or
environment:

- Operating System (OS): Windows 11
- OS Version: 22631.4249
- Browser (if applicable):
- Browser Version (if applicable):
- Project Version (if applicable):

**Comment by FredHappyface** [comment]
Hey thanks for the issue. Not managed to reproduce this locally. Though I might be misunderstanding. Do you mind adding a code snipper for a program that causes this? Any arg processing is expected to be contianed in a run_function/ handler of sorts

**Comment by mokurin000** [comment]
> Hey thanks for the issue. Not managed to reproduce this locally. Though I might be misunderstanding. Do you mind adding a code snipper for a program that causes this? Any arg processing is expected to be contianed in a run_function/ handler of sorts

https://github.com/mokurin000/fuckingfast-batch-download

comment the `gui="freesimplegui"` and run `python -m fuckingfast_batch_download.gui`, then close it with Windows decoration, it will throw an exception in terminal
lemme take a screenshot for you

**Comment by mokurin000** [comment]
> Hey thanks for the issue. Not managed to reproduce this locally. Though I might be misunderstanding. Do you mind adding a code snipper for a program that causes this? Any arg processing is expected to be contianed in a run_function/ handler of sorts

```text
fuckingfast-batch-download on  master [!] is 📦 v0.1.0 via 🐍 v3.12.3 
❯ micromamba activate fuckingfast_batch_download

fuckingfast-batch-download on  master [!] is 📦 v0.1.0 via 🐍 v3.11.10 via 🅒 fuckingfast_batch_download
❯ python -m fuckingfast_batch_download.gui      
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\neko_poly000\Documents\Repos\fuckingfast-batch-download\src\fuckingfast_batch_download\gui.py", line 33, in <module>
    gui()
  File "C:\Users\neko_poly000\micromamba\envs\fuckingfast_batch_download\Lib\site-packages\cli2gui\decorators.py", line 288, in inner
    return callingFunction(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\neko_poly000\Documents\Repos\fuckingfast-batch-download\src\fuckingfast_batch_download\__main__.py", line 153, in main
    blocking_run(args)
  File "C:\Users\neko_poly000\Documents\Repos\fuckingfast-batch-download\src\fuckingfast_batch_download\__main__.py", line 60, in blocking_run
    asyncio.run(run(args))
  File "C:\Users\neko_poly000\micromamba\envs\fuckingfast_batch_download\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\neko_poly000\micromamba\envs\fuckingfast_batch_download\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\neko_poly000\micromamba\envs\fuckingfast_batch_download\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\neko_poly000\Documents\Repos\fuckingfast-batch-download\src\fuckingfast_batch_download\__main__.py", line 100, in run
    config.TIMEOUT_PER_PAGE = int(args.timeout)
                                  ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'timeout'
```

My steps:
1. run `python -m fuckingfast_batch_download.gui`
2. close the program via system decoration close button

![image](https://github.com/user-attachments/assets/f41fa540-afe7-4068-b63d-d0ab90b41b29)

If I click the Exit button, everything works fine

**Comment by FredHappyface** [comment]
Perfect, thank you so much for that - I'll take a look now :)

**Comment by FredHappyface** [comment]
Ok yeah the problem is that args can be passed as None to the run_function when the window is closed which results in a crash

The current workaround is 

![image](https://github.com/user-attachments/assets/494e0e83-b0bb-4af7-8e71-aa87832c6463)

But yeah I'll see what I can do to rectify that!

**Comment by FredHappyface** [comment]
Tested this locally and looks to be fixed. If you could confirm you're happy then that'd be a massive help! Thansk for flagging this - there are a couple part of the cli2gui codebase which are quite difficult to follow tbh 

https://github.com/FHPythonUtils/Cli2Gui/tree/fix18

**Comment by mokurin000** [comment]
> Tested this locally and looks to be fixed. If you could confirm you're happy then that'd be a massive help! Thansk for flagging this - there are a couple part of the cli2gui codebase which are quite difficult to follow tbh
> 
> https://github.com/FHPythonUtils/Cli2Gui/tree/fix18

I want to try it, but when I lowered my head, I suddenly felt very dizzy. I should rest for a while. I will give you an reply when I test it.

**Comment by FredHappyface** [comment]
Gosh yeah of course. Take your time, and take care!

**Comment by mokurin000** [comment]
> Tested this locally and looks to be fixed. If you could confirm you're happy then that'd be a massive help! Thansk for flagging this - there are a couple part of the cli2gui codebase which are quite difficult to follow tbh
> 
> https://github.com/FHPythonUtils/Cli2Gui/tree/fix18

it works!

![image](https://github.com/user-attachments/assets/11f6911a-89d0-461d-8b3f-02474f080b08)
