### ISSUE TITLE
Adding "input()" as element to Cli2gui.

### ISSUE THREAD

**Issue by marcobaturan** [FHPythonUtils/Cli2Gui#4]
## Feature
- [x] I have read the comment above and have completed each step
- [ ] I have filled in each heading below

### Describe the solution you'd like
A possible options it's to add "input ()" build-in function like readable option.

### Describe alternatives you've considered
Instead of;
@Cli2Gui(argparse="argparse"...)
Can be possible put ...?
@Cli2Gui(argparse="inpu" ...)
Def func():
   Var=imput ("...")

Many thanks in advance.

**Comment by FredHappyface** [comment]
Sounds like a pretty good idea. I'll take a look at this over the next few weeks

**Comment by marcobaturan** [comment]
Thanks. Sorry if now I can't help. Because I have too much work. But after
read your code (BTW; beautiful!) I think the easy way it's recycling one of
the existing  functions. And adapt the code to parsing in a list the
population of inputs and the texts between "".
It's my two cents.

**Comment by FredHappyface** [comment]
Should be addressed in the latest version
